"""Updates schema

Revision ID: 8555aa773b95
Revises: 
Create Date: 2020-05-14 11:34:41.849675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8555aa773b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals')
    op.add_column('admins', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'menu', ['menu_id'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'menu_id')
    op.drop_column('admins', 'password_hash')
    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='meals_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meals_pkey')
    )
    # ### end Alembic commands ###
