"""Menu schema changes

Revision ID: 89ed60cb2526
Revises: 9670815bc195
Create Date: 2020-05-14 17:00:17.722555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ed60cb2526'
down_revision = '9670815bc195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('description', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('price', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('menu', 'menu_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('menu', 'title')
    op.drop_column('menu', 'price')
    op.drop_column('menu', 'description')
    # ### end Alembic commands ###
