"""Changes schema

Revision ID: 9670815bc195
Revises: 8555aa773b95
Create Date: 2020-05-14 11:54:00.279530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9670815bc195'
down_revision = '8555aa773b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('pass_code', sa.String(), nullable=True))
    op.drop_column('admins', 'password_hash')
    op.add_column('users', sa.Column('pass_code', sa.String(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_code')
    op.add_column('admins', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('admins', 'pass_code')
    # ### end Alembic commands ###
