"""Changes schema

Revision ID: f1f0d1f7a624
Revises: 89ed60cb2526
Create Date: 2020-05-14 21:56:06.926677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f0d1f7a624'
down_revision = '89ed60cb2526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery')
    # ### end Alembic commands ###
